name: 编译

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: 安装 JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: 安装 Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: 安装 Android SDK
      uses: android-actions/setup-android@v3

    - name: 同意 sdk 许可证
      run: yes | sdkmanager --licenses || true

    - name: 执行权限
      run: cd biliSendCommAntifraud && chmod +x gradlew
    - name: 编译
      run: cd biliSendCommAntifraud && ./gradlew :app:assembleRelease
    - name: 上传产物
      uses: actions/upload-artifact@v4
      with:
        name: APKs
        path: '**/build/outputs/apk/**/*.apk'
